language: java
sudo: false
before_install:
- cp settings.xml $HOME/.m2/settings.xml
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: script
  script: "mvn deploy -q -DskipTests=true"
  on:
    condition: $TRAVIS_EVENT_TYPE = cron
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ada7bbc05b2a99cff40
    on_success: change
    on_failure: always
    on_start: never
